/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.SachController;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Sach;

/**
 *
 * @author Admin
 */
public class fmSach extends javax.swing.JFrame {

    private SachController sCtl;

    /**
     * Creates new form fmSach
     */
    public fmSach() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfMaS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfTenS = new javax.swing.JTextField();
        tfTacgia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNamXB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfDongia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        cmbNXB = new javax.swing.JComboBox<>();
        btAdd = new javax.swing.JButton();
        btFix = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btCancle = new javax.swing.JButton();
        btXemNXB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        btFirst = new javax.swing.JButton();
        Spinner = new javax.swing.JSpinner();
        btLast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sách");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản Lý Danh Mục Sách", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        jLabel1.setText("Mã sách:");

        tfMaS.setEnabled(false);

        jLabel2.setText("Tên sách:");

        jLabel3.setText("Tác giả:");

        jLabel4.setText("Năm xuất bản:");

        jLabel5.setText("Đơn giá:");

        jLabel6.setText("Mã NXB:");

        btExit.setText("Thoát");

        btAdd.setText("Thêm");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btFix.setText("Sửa");
        btFix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFixActionPerformed(evt);
            }
        });

        btDelete.setText("Xóa");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btCancle.setText("Hủy");
        btCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancleActionPerformed(evt);
            }
        });

        btXemNXB.setText("Xem TT NXB");
        btXemNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXemNXBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tfTenS))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tfMaS)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTacgia)
                            .addComponent(tfNamXB))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(cmbNXB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tfDongia))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btFix)
                        .addGap(18, 18, 18)
                        .addComponent(btDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btCancle)
                        .addGap(18, 18, 18)
                        .addComponent(btExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btXemNXB)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfMaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfDongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfTenS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(cmbNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExit)
                    .addComponent(btAdd)
                    .addComponent(btFix)
                    .addComponent(btDelete)
                    .addComponent(btCancle)
                    .addComponent(btXemNXB))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tác Giả", "Năm XB", "Đơn giá", "Mã NXB"
            }
        ));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb);
        if (tb.getColumnModel().getColumnCount() > 0) {
            tb.getColumnModel().getColumn(0).setPreferredWidth(15);
            tb.getColumnModel().getColumn(3).setPreferredWidth(10);
            tb.getColumnModel().getColumn(4).setPreferredWidth(15);
            tb.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        btFirst.setText("<<");
        btFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFirstActionPerformed(evt);
            }
        });

        btLast.setText(">>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Spinner, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(btLast, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        sCtl = new SachController();
        sCtl.bookToTable(tb);
        showTextField(false);
        sCtl.hienListNXB(cmbNXB);
    }//GEN-LAST:event_formWindowOpened

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        String current = btAdd.getText();
        if (current.equals("Thêm")) {
            btAdd.setText("Lưu");
            showTextField(true);
            tfMaS.setText(sCtl.createMaSach());
            btDelete.setEnabled(false);
            btFix.setEnabled(false);

        } else {

            String mas = gt(tfMaS);
            String tens = gt(tfTenS);
            String tacgia = gt(tfTacgia);
            String namxb = gt(tfNamXB);
            Float dongia = Float.valueOf(gt(tfDongia));
            String manxb = gt(cmbNXB);
            Sach s = new Sach(mas, tens, tacgia, namxb, dongia, manxb);
            s.add();
            sCtl.bookToTable(tb);
            resetTextFields();
            btAdd.setText("Thêm");
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancleActionPerformed
        // TODO add your handling code here:

        btAdd.setText("Thêm");

        btFix.setText("Sửa");

        showTextField(false);
        resetTextFields();
    }//GEN-LAST:event_btCancleActionPerformed

    private void btFixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFixActionPerformed
        // TODO add your handling code here:
        String current = btFix.getText();
        if (current.equals("Sửa")) {
            btFix.setText("Lưu");
            showTextField(true);
            btAdd.setEnabled(false);
            btDelete.setEnabled(false);
        } else {
            String mas = gt(tfMaS);
            String tens = gt(tfTenS);
            String tacgia = gt(tfTacgia);
            String namxb = gt(tfNamXB);
            Float dongia = Float.valueOf(gt(tfDongia));
            String manxb = gt(cmbNXB);
            Sach s = new Sach(mas, tens, tacgia, namxb, dongia, manxb);
            s.fix();
            sCtl.bookToTable(tb);
            showTextField(false);
            resetTextFields();
            btFix.setText("Sửa");
        }
    }//GEN-LAST:event_btFixActionPerformed

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        // TODO add your handling code here:
        int row = tb.getSelectedRow();
        tfMaS.setText(tb.getValueAt(row, 0).toString());
        tfTenS.setText(tb.getValueAt(row, 1).toString());
        tfTacgia.setText(tb.getValueAt(row, 2).toString());
        tfNamXB.setText(tb.getValueAt(row, 3).toString());
        tfDongia.setText(tb.getValueAt(row, 4).toString());
        cmbNXB.setSelectedItem(tb.getValueAt(row, 5).toString());
    }//GEN-LAST:event_tbMouseClicked

    private void btXemNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXemNXBActionPerformed
        // TODO add your handling code here:

        fmNXB nxb = new fmNXB();
        nxb.setManxb(gt(cmbNXB));
        nxb.setVisible(true);
        nxb.setAlwaysOnTop(true);
    }//GEN-LAST:event_btXemNXBActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        if (tb.getSelectedColumn() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Chọn hàng trong bảng để xóa!");
            return;
        }
        int ck = JOptionPane.showConfirmDialog(rootPane, "Xóa Sach" + gt(tfTenS));
        if (ck == JOptionPane.YES_OPTION) {
            String mas = gt(tfMaS);
            String tens = gt(tfTenS);
            String tacgia = gt(tfTacgia);
            String namxb = gt(tfNamXB);
            Float dongia = Float.valueOf(gt(tfDongia));
            String manxb = gt(cmbNXB);
            Sach s = new Sach(mas, tens, tacgia, namxb, dongia, manxb);
            s.delete();
            sCtl.bookToTable(tb);
            showTextField(false);
            resetTextFields();

        }

    }//GEN-LAST:event_btDeleteActionPerformed

    private void btFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFirstActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btFirstActionPerformed

    private void resetTextFields() {
        btAdd.setEnabled(true);
        btFix.setEnabled(true);
        btDelete.setEnabled(true);
        tfDongia.setText("");
        tfMaS.setText("");
        tfNamXB.setText("");
        tfTacgia.setText("");
        tfTenS.setText("");

    }

    private String gt(JTextField tf) {
        return tf.getText().trim();
    }

    private String gt(JComboBox cmb) {
        return cmb.getSelectedItem().toString();
    }

    /**
     * @param args the command line arguments
     */
    

    private void showTextField(boolean ck) {

        tfTenS.setEnabled(ck);
        tfTacgia.setEnabled(ck);
        tfNamXB.setEnabled(ck);
        tfDongia.setEnabled(ck);
        cmbNXB.setEnabled(ck);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Spinner;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCancle;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btFirst;
    private javax.swing.JButton btFix;
    private javax.swing.JButton btLast;
    private javax.swing.JButton btXemNXB;
    private javax.swing.JComboBox<String> cmbNXB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb;
    private javax.swing.JTextField tfDongia;
    private javax.swing.JTextField tfMaS;
    private javax.swing.JTextField tfNamXB;
    private javax.swing.JTextField tfTacgia;
    private javax.swing.JTextField tfTenS;
    // End of variables declaration//GEN-END:variables
}
